# Generated by Django 2.2.12 on 2022-06-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_latlon'),
    ]

    operations = [
        migrations.CreateModel(
            name='heat_orange',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='heat_read',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
